# Generated by Django 2.0.7 on 2018-07-06 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qs_app', '0002_meal_foods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealFood',
        ),
    ]
