# Generated by Django 2.0.7 on 2018-07-09 22:48

from django.db import migrations

def load_meal_data:
    Meal = apps.get_model('qs_app', 'Meal')

    Meal(name="Breakfast").save()
    Meal(name="Snack").save()
    Meal(name="Lunch").save()
    Meal(name="Dinner").save()


class Migration(migrations.Migration):

    dependencies = [
        ('qs_app', '0003_delete_mealfood'),
    ]

    operations = [
        migrations.RunPython(load_meal_data),
    ]
